federation_version: =2.3.2
subgraphs:
  galoy:
    routing_url: url
    schema:
      file: ../galoy/dev/config/apollo-federation/supergraph.graphql
  circles:
    routing_url: url
    schema:
      file: ../blink-circles/src/graphql/schema.graphql
  kyc:
    routing_url: url
    schema:
      file: ../blink-kyc/app/graphql/schema.graphql
