[default.extend-identifiers]
youreConverting = "youreConverting"
hace = "hace"
"BA" = "BA"
"FO" = "FO"

[files]
extend-exclude = ["*.svg", "app/i18n/raw-i18n", "earns-utils.test.ts", "*.plist", "*.pbxproj", "Appfile", "google-services.json", "patches", "ci/tasks/*"]
